### ISSUE TITLE
dev with error

### ISSUE THREAD

**Issue by huanghaiyang** [zippyui/react-class#2]
when i execute 'npm run dev',then webpack success

but when i access localhost:8080 or localhost:8080/index.html , the chrome console appears one error like bellow:
bundle.js:596 Uncaught TypeError: Super expression must either be null or a function, not object

how can i develope this project .

**Comment by radubrehar** [comment]
Check it out now, as https://github.com/zippyui/react-class/commit/e3f40d61fb7770bbe61f01608e4013f8b0619c5f fixes the issue.
